path:
  # --- shared
  calendar_path: E:\OneDrive\Data\Calendar\cne_calendar.csv
  root_dir: E:\OneDrive\Data\tushare
  daily_data_root_dir: E:\OneDrive\Data\tushare\by_date
  db_struct_path: E:\OneDrive\Data\tushare\db_struct.yaml
  alternative_dir: E:\OneDrive\Data\Alternative
  market_index_path: E:\OneDrive\Data\Market\index.xlsx
  by_instru_pos_dir: E:\OneDrive\Data\tushare\by_instrument\position
  by_instru_pre_dir: E:\OneDrive\Data\tushare\by_instrument\preprocess
  by_instru_min_dir: E:\OneDrive\Data\tushare\by_instrument\minute_bar
  instru_info_path: E:\OneDrive\Data\tushare\instruments.csv

  # --- project
  project_root_dir: E:\Data\Projects\CTA_ML_V4

mkt_idxes:
  equity: 881001.WI
  commodity: NH0100.NHF

universe:
  AU.SHF:
    sectorL0: C
    sectorL1: AUG
  AG.SHF:
    sectorL0: C
    sectorL1: AUG
  CU.SHF:
    sectorL0: C
    sectorL1: MTL
  AL.SHF:
    sectorL0: C
    sectorL1: MTL
  PB.SHF:
    sectorL0: C
    sectorL1: MTL
  ZN.SHF:
    sectorL0: C
    sectorL1: MTL
  NI.SHF:
    sectorL0: C
    sectorL1: MTL
  SN.SHF:
    sectorL0: C
    sectorL1: MTL
  SS.SHF:
    sectorL0: C
    sectorL1: MTL
  AO.SHF:
    sectorL0: C
    sectorL1: MTL
  A.DCE:
    sectorL0: C
    sectorL1: OIL
  B.DCE:
    sectorL0: C
    sectorL1: OIL
  M.DCE:
    sectorL0: C
    sectorL1: OIL
  P.DCE:
    sectorL0: C
    sectorL1: OIL
  Y.DCE:
    sectorL0: C
    sectorL1: OIL
  OI.ZCE:
    sectorL0: C
    sectorL1: OIL
  RM.ZCE:
    sectorL0: C
    sectorL1: OIL
  RU.SHF:
    sectorL0: C
    sectorL1: CHM
  BR.SHF:
    sectorL0: C
    sectorL1: CHM
  BU.SHF:
    sectorL0: C
    sectorL1: CHM
  FU.SHF:
    sectorL0: C
    sectorL1: CHM
  L.DCE:
    sectorL0: C
    sectorL1: CHM
  V.DCE:
    sectorL0: C
    sectorL1: CHM
  EB.DCE:
    sectorL0: C
    sectorL1: CHM
  EG.DCE:
    sectorL0: C
    sectorL1: CHM
  PP.DCE:
    sectorL0: C
    sectorL1: CHM
  PG.DCE:
    sectorL0: C
    sectorL1: CHM
  MA.ZCE:
    sectorL0: C
    sectorL1: CHM
  TA.ZCE:
    sectorL0: C
    sectorL1: CHM
  RB.SHF:
    sectorL0: C
    sectorL1: BLK
  HC.SHF:
    sectorL0: C
    sectorL1: BLK
  I.DCE:
    sectorL0: C
    sectorL1: BLK
  J.DCE:
    sectorL0: C
    sectorL1: BLK
  JM.DCE:
    sectorL0: C
    sectorL1: BLK
  SF.ZCE:
    sectorL0: C
    sectorL1: BLK
  SM.ZCE:
    sectorL0: C
    sectorL1: BLK
  ZC.ZCE:
    sectorL0: C
    sectorL1: BLK
  FG.ZCE:
    sectorL0: C
    sectorL1: BLK
  SA.ZCE:
    sectorL0: C
    sectorL1: BLK
  UR.ZCE:
    sectorL0: C
    sectorL1: BLK
  AP.ZCE:
    sectorL0: C
    sectorL1: AGR
  CF.ZCE:
    sectorL0: C
    sectorL1: AGR
  SR.ZCE:
    sectorL0: C
    sectorL1: AGR
  CY.ZCE:
    sectorL0: C
    sectorL1: AGR
  CJ.ZCE:
    sectorL0: C
    sectorL1: AGR
  PK.ZCE:
    sectorL0: C
    sectorL1: AGR
  JD.DCE:
    sectorL0: C
    sectorL1: AGR
  LH.DCE:
    sectorL0: C
    sectorL1: AGR
  C.DCE:
    sectorL0: C
    sectorL1: AGR
  CS.DCE:
    sectorL0: C
    sectorL1: AGR

available:
  win: 10
  amount_threshold: 100000.00
prd:
  wins: [ 5, 10 ]
sim:
  wins: [ 1 ]

# ------- factors -------
factors:
  MTM:
    wins: [ 1, 2, 3, 5, 10, 20, 120, 240 ]
  SKEW:
    wins: [ 10, 20, 60, 120 ]
  KURT:
    wins: [ 5, 10, 20, 60, 120, 240 ] #
  RS:
    wins: [ 20, 60, 120, 240 ]
  BASIS:
    wins: [ 10, 20, 60, 120, 240 ]
  TS:
    wins: [ 10, 20, 60, 120, 240 ]
  LIQUIDITY:
    wins: [ 10, 20, 60, 120, 240 ]
  SIZE:
    wins: [ 10, 20, 60, 120, 240 ]
  MF:
    wins: [ 1, 3, 5, 10 ]
  JUMP:
    wins: [ 1, 3, 5, 10 ]
  CTP:
    wins: [ 60, 120, 180 ]
    lbds: [ 0.5, 0.9, 0.95 ]
  CTR:
    wins: [ 60, 120, 180 ]
    lbds: [ 0.2, 0.5, 0.9 ]
  CVP:
    wins: [ 60, 120, 180 ]
    lbds: [ 0.5, 0.9, 0.95 ]
  SMT:
    wins: [ 1, 3, 5 ]
    lbds: [ 0.2, 0.5, 0.8 ]
  SPDWEB:
    wins: [ 1, 3, 5 ]
    lbds: [ 0.1, 0.2, 0.4 ]
  ACR:
    wins: [ 5, 8, 13, 21 ]
  IDV:
    wins: [ 5, 8, 13, 21, 34, 55 ]
  CNVG:
    wins: [ 5, 10, 20, 60, 120, 240 ]
  REOC:
    wins: [ 1, 2, 3, 5, 10, 20, 120, 240 ]
  NPLS:
    wins: [ 3, 5, 10, 20, 60, 120, 240 ]
  WSPLIT:
    wins: [ 1, 3, 5 ]
    lbds: [ 0.1, 0.2, 0.4 ]
  S0BETA:
    wins: [ 10, 20, 60, 120 ]
  ONR:
    wins: [ 3, 5, 10, 20, 60, 120, 240 ]
  MPH:
    wins: [ 60, 120, 180 ]
    lbds: [ 0.80, 1.00 ]
  MPC:
    wins: [ 60, 120, 180 ]
    lbds: [ 0.80, 1.00 ]

# ------- factors universe -------
factors_universe_options:
  raw:
    Opn:
      - [ MTM, MTMDIF ]
      - [ SKEW, SKEW120 ]
      - [ KURT, KURTDIF ]
      - [ RS, RSPA240 ]
      - [ BASIS, BASIS120 ]
      - [ BASIS, BASISRES010 ]
      - [ TS, TS240 ]
      - [ LIQUIDITY, LIQUIDITY240 ]
      - [ CTP, CTP060L95 ]
      - [ CVP, CVP060L95 ]
      - [ SIZE, SIZEDIF ]
      - [ SPDWEB, SPDWEB001L10 ]
      - [ ACR, ACR008vol ]
      - [ REOC, REOCDIF ]
      - [ NPLS, NPLSDIF ]
      - [ S0BETA, S0BETA020 ]
      - [ ONR, ONR120 ]
      - [ MPH, MPH120L80 ]
    Cls:
      - [ MTM, MTMDIF ]
      - [ SKEW, SKEW120 ]
      - [ KURT, KURTDIF ]
      - [ RS, RSPA240 ]
      - [ BASIS, BASIS120 ]
      - [ BASIS, BASISRES010 ]
      - [ TS, TS240 ]
      - [ LIQUIDITY, LIQUIDITY240 ]
      - [ CTP, CTP060L95 ]
      - [ CVP, CVP060L95 ]
      - [ SIZE, SIZEDIF ]
      - [ ACR, ACR008vol ]
      - [ REOC, REOCDIF ]
      - [ NPLS, NPLSDIF ]
      - [ S0BETA, S0BETA020 ]
      - [ ONR, ONR120 ]
      - [ MPH, MPH120L80 ]
  neu:
    Opn:
      - [ MTM, MTMDIF ]
      - [ SKEW, SKEW020D ]
      - [ KURT, KURTDIF ]
      - [ RS, RSPA240 ]
      - [ BASIS, BASIS120 ]
      - [ BASIS, BASISRES010 ]
      - [ TS, TS240 ]
      - [ LIQUIDITY, LIQUIDITY240 ]
      - [ CTP, CTP120L95 ]
      - [ CVP, CVP120L95 ]
      - [ SIZE, SIZEDIF ]
      - [ SPDWEB, SPDWEB001L10 ]
      - [ ACR, ACR008vol ]
      - [ REOC, REOCDIF ]
      - [ NPLS, NPLSDIF ]
      - [ S0BETA, S0BETA020 ]
      - [ ONR, ONR120 ]
    Cls:
      - [ MTM, MTMDIF ]
      - [ SKEW, SKEW020D ]
      - [ KURT, KURTDIF ]
      - [ RS, RSPA240 ]
      - [ BASIS, BASIS120 ]
      - [ BASIS, BASISRES010 ]
      - [ TS, TS240 ]
      - [ LIQUIDITY, LIQUIDITY240 ]
      - [ CTP, CTP120L95 ]
      - [ CVP, CVP120L95 ]
      - [ SIZE, SIZEDIF ]
      - [ ACR, ACR008vol ]
      - [ REOC, REOCDIF ]
      - [ NPLS, NPLSDIF ]
      - [ S0BETA, S0BETA020 ]
      - [ ONR, ONR120 ]

# ------- models -------
test_models:
  #  - model_type: BASELINE
  #    trn_win: 240
  #    using_instru: false
  #    classification: false
  #    cv: 0
  #    early_stopping: 0
  #    hyper_param_grids:
  #  - model_type: BASELINE
  #    trn_win: 120
  #    using_instru: false
  #    classification: false
  #    cv: 0
  #    early_stopping: 0
  #    hyper_param_grids:
  #  - model_type: BASELINE
  #    trn_win: 60
  #    using_instru: false
  #    classification: false
  #    cv: 0
  #    early_stopping: 0
  #    hyper_param_grids:
  #  - model_type: BASELINE
  #    trn_win: 30
  #    using_instru: false
  #    classification: false
  #    cv: 0
  #    early_stopping: 0
  #    hyper_param_grids:
  #  - model_type: LINEAR
  #    trn_win: 30
  #    using_instru: false
  #    classification: false
  #    cv: 0
  #    early_stopping: 0
  #    hyper_param_grids:
  #  - model_type: RIDGE
  #    trn_win: 30
  #    using_instru: false
  #    classification: false
  #    cv: 5
  #    early_stopping: 0
  #    hyper_param_grids:
  #      alpha: [ 0.1, 1, 10 ]
  #  - model_type: LOGISTIC
  #    trn_win: 30
  #    using_instru: false
  #    classification: true
  #    cv: 5
  #    early_stopping: 0
  #    hyper_param_grids:
  #      C: [ 5, 10, 20, 50, 100 ]
  #  - model_type: SVM
  #    trn_win: 30
  #    using_instru: false
  #    classification: true
  #    cv: 5
  #    early_stopping: 0
  #    hyper_param_grids:
  #      C: [ 0.01, 0.02, 0.05, 0.1 ]
  #  - model_type: MLP
  #    trn_win: 240
  #    using_instru: false
  #    classification: true
  #    cv: 5
  #    early_stopping: 0
  #    hyper_param_grids:
  #      hidden_layer_sizes: [ [ 3, 3, 3 ], [ 5, 5, 5 ], [ 8, 8, 8 ] ]
  #      alpha: [ 0.01, 0.001 ]
  - model_type: LGBM
    trn_win: 240
    using_instru: true
    classification: true
    cv: 5
    early_stopping: 5
    hyper_param_grids:
      boosting_type: [ "gbdt" ]
      n_estimators: [ 50 ]
      max_depth: [ 2, ]
      max_leaves: [ 3, ]
      learning_rate: [ 0.01, 0.05, 0.1 ]
      metric: [ "binary_logloss" ] # ["l1", "l2"] for regressor, ["binary_logloss"] for classifier
  - model_type: XGB
    trn_win: 240
    using_instru: true
    classification: true
    cv: 5
    early_stopping: 5
    hyper_param_grids:
      booster: [ "gbtree" ] # ["gbtree", "gblinear", "dart"]
      n_estimators: [ 50 ]
      max_depth: [ 2 ]
      max_leaves: [ 3 ]
      learning_rate: [ 0.01, 0.05, 0.1 ]
      objective: [ "binary:logistic" ] # ["reg:squarederror", "reg:absoluteerror", "binary:logistic"]
CONST:
  INIT_CASH: 100_000_000
  COST_RATE: 0.0003
  SECTORS: [ "AUG", "MTL", "BLK", "OIL", "CHM", "AGR" ]
  #  SECTORS: [ "BLK", "OIL", "CHM", "AGR" ]
  LAG: 1
